config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'homes', to: 'homes#show'
  root 'homes#show'
  resources :users, only: %i[show new edit create update destroy]
  resources :articles, only: %i[show new edit create update destroy] do
    resources :comments, only: %i[edit create update destroy] do
      member do
        get :approve
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  extend Enumerize

  belongs_to :user
  belongs_to :article

  validates :text, presence: true

  enumerize :status, in: [:unapproved, :approved]
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  load_and_authorize_resource :article

  def show; end

  def edit; end

  def create
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@article), notice: '登録に成功しました' }
      else
        format.html { redirect_to article_path(@article), notice: '登録に失敗しました' }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :article
  load_and_authorize_resource

  def show; end

  def edit; end

  def create
    @comment.article = @article
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        NoticeMailer.sendmail_confirm(@comment.user, @comment.article).deliver_now
        format.html { redirect_to article_path(@article), notice: '登録に成功しました' }
      else
        format.html { redirect_to article_path(@article), notice: '登録に失敗しました' }
      end
    end
  end

  def update
    @comment.update(comment_params)
    if @comment.save
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
    end
  end

  def approve
    @comment.status = params[:status]
    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/views/comments/_form.html.haml
= simple_form_for(Comment.new, url: article_comments_path(article)) do |f|
  = f.input :text
  = f.submit

app/views/comments/_pickup.html.haml
%table
  %thead
    %tr
      %th COMMENT
      %th
      %th
      %th
  %tbody
    - comments.each do |comment|
      - if comment.status == "approved"
        %tr
          %td= simple_format(comment.text)
          - if comment.user == current_user
            %td= link_to "edit", edit_article_comment_path(comment.article, comment)
            %td= link_to "destroy", article_comment_path(comment.article, comment), method: :delete
          %td= comment.status
      - else
        %tr
          %td
            - if comment.article.user = current_user
              / jsの場合 select
              / = simple_form_for comment, url: approve_article_comment_path(comment.article, comment) do |f|
              /   =f.input :status, onchange: "submit(this.form)", input_html: {class: 'js-comment_status'}
              / %p= comment.status
              = link_to "approved", approve_article_comment_path(comment.article, comment, status: "approved")
            - else
              = comment.status

app/views/comments/edit.html.haml
= simple_form_for(@comment, url: article_comment_path(@comment.article, @comment)) do |f|
  = f.input :text
  = f.submit