config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'homes', to: 'homes#show'
  root 'homes#show'
  resources :users, only: %i[show new edit create update destroy]
  resources :articles, only: %i[show new edit create update destroy] do
    resources :comments, only: %i[edit create update destroy] do
      member do
        get :approve
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :tel, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show; end

  def edit; end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :tel)
    end
end

app/views/users/_form.html.haml
= simple_form_for user, html: {'data-parsley-validate' => '', 'parsley-use-html5-constraints' => false, 'data-parsley-trigger' => "keyup focusout change input"} do |f|
  = f.input :name
  = f.input :email
  = f.input :tel
  = f.submit

app/views/users/edit.html.haml
= render 'form', user: @user

app/views/users/index.html.haml
%h1 ユーザー一覧
= link_to "ユーザー追加", new_user_path
= link_to "ログアウト", destroy_user_session_path, method: :delete

%table
  %thead
    %tr
      %th ID
      %th 名前
      %th メールアドレス
      %th TEL
      %th
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.name
        %td= user.email
        %td= user.tel
        %td= link_to '編集', edit_user_path(user)
        %td= link_to '削除', user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' }

app/views/users/new.html.haml
= link_to '登録', '#modal', data: {'remodal-target': 'modal'}
.remodal{data: {remodal_id: "modal"}}
  %button.remodal-close{data: {remodal_action: "close"}}
  #modal__content
    = render 'form', user: @user
= link_to "トップページへ", root_path

app/views/users/show.html.haml
= render "layouts/header"
.user_show_page
  .user__area
    = @user.name
    = @user.email
    = @user.tel
  - if @user.articles.present?
    - if articles = @user.articles.article_publish.presence
      %h2 公開済み記事一覧
      - articles.each do |article|
        .article_area
          = article.name
          = simple_format(article.description)
          = image_tag article.image
        - if article.comments.present?
          = render "comments/pickup", comments: article.comments
  - if @user = current_user
    - if articles = @user.articles.article_draft.presence
      %h2 下書き記事一覧
      - articles.each do |article|
        .article_area
          = article.name
          = simple_format(article.description)
          = image_tag article.image
          = link_to "edit", edit_article_path(article)
          = link_to "destroy", article_path(article), method: :delete
  = link_to "トップページへ", root_path